version: '20.10.7' # docker -v 버전을 입력

services: # 실행하려는 컨테이너들을 정의
    jenkins: # 서비스의 이름
    image: 'jenkins/jenkins' # 사용할 도커 이미지
    # 명시적으로 중지되거나, Docker 자체가 중지되는 경우 재시작
    restart: unless-stopped
    user: root
    privileged: true # permission denied 관련 설정
    ports: # 사용할 포트 번호 설정
    - '9090:8080'
    volumes: # 로컬 디렉토리의 특정 경로를 컨테이너 내부로 마운트할 수 있음
    - '/home/ubuntu/docker/jenkins-data:/var/jenkins_home'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '$HOME:/home'
    container_name: 'jenkins'
    command: 'mvn -U clean spring-boot:run -Dspring-boot.run.jvmArguments="-Dkms.url=ws://52.79.162.52:8888/kurento"'
